controller_list:
  - name: fake_panda_1_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda_2_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_dual_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_hand_1_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_finger_joint1
  - name: fake_hand_2_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_2_finger_joint1
initial:  # Define initial robot poses per group
  - group: panda_1
    pose: home
  - group: panda_2
    pose: home
